# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7-base-box"

  config.vm.network "private_network", ip: "192.168.50.101"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision :shell, path: 'provision.sh', privileged: true
  # Requires vagrant-vbguest plugin
  config.vbguest.auto_update = true
end
